"""Tests for trajectory and thermo range extraction utilities."""

import sys
from pathlib import Path

import pytest

from lammpalyze.chop import chop_lammpstrj, chop_thermo_log, chopthermo_main, default_segment_path


def test_chop_lammpstrj_writes_complete_frames_and_default_name(tmp_path: Path):
    """Extract complete LAMMPS dump frames in an inclusive timestep range."""

    trajectory = tmp_path / "sample.traj"
    trajectory.write_text(
        """# generated by test
ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.0 0.0 0.0
2 1 0.1 0.1 0.1
ITEM: TIMESTEP
10
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.2 0.2 0.2
2 1 0.3 0.3 0.3
ITEM: TIMESTEP
20
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.4 0.4 0.4
2 1 0.5 0.5 0.5
ITEM: TIMESTEP
30
ITEM: NUMBER OF ATOMS
2
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.6 0.6 0.6
2 1 0.7 0.7 0.7
""",
        encoding="utf-8",
    )

    output_path, frames_written = chop_lammpstrj(trajectory, 10, 20)

    assert output_path == tmp_path / "sample_10_20.traj"
    assert frames_written == 2
    output = output_path.read_text(encoding="utf-8")
    assert output.startswith("# generated by test\n")
    assert output.count("ITEM: TIMESTEP") == 2
    assert "\n10\n" in output
    assert "\n20\n" in output
    assert "\n0\n" not in output
    assert "\n30\n" not in output


def test_chop_lammpstrj_tolerates_trailing_empty_frame_marker(tmp_path: Path):
    """A final dangling timestep marker should not spoil copied complete frames."""

    trajectory = tmp_path / "truncated.traj"
    trajectory.write_text(
        """ITEM: TIMESTEP
0
ITEM: NUMBER OF ATOMS
1
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.0 0.0 0.0
ITEM: TIMESTEP
10
ITEM: NUMBER OF ATOMS
1
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.1 0.1 0.1
ITEM: TIMESTEP
""",
        encoding="utf-8",
    )

    output_path, frames_written = chop_lammpstrj(trajectory, 10, 20)

    assert frames_written == 1
    assert output_path.read_text(encoding="utf-8").count("ITEM: TIMESTEP") == 1


def test_chop_lammpstrj_preserves_destination_when_range_is_empty(tmp_path: Path):
    """Do not leave an empty or overwritten export after a failed range cut."""

    trajectory = tmp_path / "sample.traj"
    trajectory.write_text(
        """ITEM: TIMESTEP
10
ITEM: NUMBER OF ATOMS
1
ITEM: BOX BOUNDS pp pp pp
0 1
0 1
0 1
ITEM: ATOMS id type x y z
1 1 0.0 0.0 0.0
""",
        encoding="utf-8",
    )
    destination = tmp_path / "existing.traj"
    destination.write_text("keep me\n", encoding="utf-8")

    with pytest.raises(ValueError, match="No trajectory frames found"):
        chop_lammpstrj(trajectory, 20, 30, destination)

    assert destination.read_text(encoding="utf-8") == "keep me\n"
    assert not list(tmp_path.glob(".existing.traj.*.tmp"))


def test_chop_lammpstrj_rejects_overwriting_its_source(tmp_path: Path):
    """Protect the source when a caller chooses it as the output path."""

    trajectory = tmp_path / "sample.traj"
    original = "trajectory contents\n"
    trajectory.write_text(original, encoding="utf-8")

    with pytest.raises(ValueError, match="different from the source"):
        chop_lammpstrj(trajectory, 0, 10, trajectory)

    assert trajectory.read_text(encoding="utf-8") == original


def test_chop_thermo_log_preserves_headered_table(tmp_path: Path):
    """Keep leading log text and thermo column headers for selected rows."""

    thermo = tmp_path / "thermo.log"
    thermo.write_text(
        """LAMMPS log header
Step Temp PotEng
0 300.0 -10.0
10 305.0 -9.0
20 310.0 -8.0
Loop time of 1.0 on 1 procs for 20 steps
""",
        encoding="utf-8",
    )
    destination = tmp_path / "slice.log"

    output_path, rows_written = chop_thermo_log(thermo, 10, 20, destination)

    assert output_path == destination
    assert rows_written == 2
    assert destination.read_text(encoding="utf-8") == (
        "LAMMPS log header\n"
        "Step Temp PotEng\n"
        "10 305.0 -9.0\n"
        "20 310.0 -8.0\n"
    )


def test_chop_thermo_log_supports_headerless_numeric_files(tmp_path: Path):
    """Headerless thermo snippets are sliced by the first numeric column."""

    thermo = tmp_path / "plain.log"
    thermo.write_text(
        """124760 1.0
124770 2.0
124780 3.0
""",
        encoding="utf-8",
    )

    output_path, rows_written = chop_thermo_log(thermo, 124770, 124770)

    assert output_path == tmp_path / "plain_124770_124770.log"
    assert rows_written == 1
    assert output_path.read_text(encoding="utf-8") == "124770 2.0\n"


def test_chopthermo_main_accepts_legacy_end_shorthand(tmp_path: Path, capsys):
    """Accept the example form ``e-125500`` as shorthand for ``-e 125500``."""

    thermo = tmp_path / "plain.log"
    thermo.write_text("124770 2.0\n125500 3.0\n", encoding="utf-8")

    exit_code = chopthermo_main(["-i", str(thermo), "-s", "124770", "e-125500"])

    assert exit_code == 0
    assert "Wrote 2 thermo row(s)" in capsys.readouterr().out
    assert default_segment_path(thermo, 124770, 125500).exists()


def test_chopthermo_main_normalizes_sys_argv_shorthand(tmp_path: Path, monkeypatch, capsys):
    """Normalize ``e-`` shorthand when the installed console script uses ``sys.argv``."""

    thermo = tmp_path / "plain.log"
    thermo.write_text("124770 2.0\n125500 3.0\n", encoding="utf-8")
    monkeypatch.setattr(
        sys,
        "argv",
        ["chopthermo", "-i", str(thermo), "-s", "124770", "e-125500"],
    )

    exit_code = chopthermo_main()

    assert exit_code == 0
    assert "Wrote 2 thermo row(s)" in capsys.readouterr().out
